Move docs to the website
ClickHouse/clickhouse-java pull request #1251
Opened 2023-02-20 09:55 UTC by mshustov

## Summary
This PR moves docs to the ClickHouse website to use the website as the main source of truth.
Also, I moved some dev instructions to `CONTRIBUTING.md` guide.

2023-02-21 01:43 UTC, zhicwu requested changes
By the way, what's the PR for moving removed content to `clickhouse-docs`?

2023-02-21 01:43 UTC, zhicwu commented on CONTRIBUTING.md
> +git clone https://github.com/[YOUR_USERNAME]/clickhouse-jdbc
Should be `clickhouse-java` right?

2023-02-21 01:43 UTC, zhicwu commented on CONTRIBUTING.md
> +We use [TestNG](http://org.testng/doc) as testing framework and for running ClickHouse Local instance [testcontainers](https://www.testcontainers.org/modules/databases/clickhouse/).
Should we format the doc so that there will be a blank line between header and paragraph?

2023-02-21 10:19 UTC, mshustov commented on CONTRIBUTING.md
> +git clone https://github.com/[YOUR_USERNAME]/clickhouse-jdbc
good catch

2023-02-21 10:21 UTC, mshustov commented
> By the way, what's the PR for moving removed content to clickhouse-docs?

Update the PR title with a link to clickhouse-docs https://github.com/ClickHouse/clickhouse-docs/pull/792

2023-02-22 00:13 UTC, zhicwu commented
Thanks @mshustov. The PR was for 0.4.0 but now it's 0.4.1 :) Will submit a PR in clickhouse-docs when I get home to fix that.

2023-02-22 00:13 UTC, merged