Remove deprecated api settings
ClickHouse/clickhouse-java pull request #1433
Opened 2023-08-28 14:02 UTC by mzitnik

## Summary
* remove deprecated API load, dump, and connect
* remove use_no_proxy settings

## Checklist
Delete items not relevant to your PR:
- [ ] Unit and integration tests covering the common scenarios were added
- [X] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

2023-08-28 14:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ClickHouse/clickhouse-java?pullRequest=1433) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ClickHouse/clickhouse-java?pullRequest=1433) before we can accept your contribution.<br/><hr/>**mzitnik** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ClickHouse/clickhouse-java?pullRequest=1433) it.</sub>

2023-08-28 15:13 UTC, mzitnik commented
@zhicwu if you can take a look i have made some cleanup

2023-08-29 00:27 UTC, zhicwu commented
There are many changes. Will review, test, and merge tonight.

2023-08-29 10:22 UTC, zhicwu requested changes

2023-08-29 10:22 UTC, zhicwu commented on clickhouse-grpc-client/src/main/java/com/clickhouse/client/grpc/ClickHouseGrpcChannelFactory.java
> -        if (config.isUseNoProxy()) {
Let's simply replace `config.isUseNoProxy()` to `config.getProxyType() == ClickHouseProxyType.DIRECT`.

2023-08-29 10:22 UTC, zhicwu commented on .github/workflows/build.yml
> +        clickhouse: ["22.8", "23.3", "23.7", "latest"]
If we wait for a few more days, we can change 23.7 to 23.8 lts :)

2023-08-29 15:52 UTC, mzitnik commented
@zhicwu do you know why SonarCloud Quality Gate failed? (nothing was changed just removed deprecated api)

2023-08-29 22:13 UTC, zhicwu approved these changes

2023-08-29 22:14 UTC, merged

2023-08-29 22:14 UTC, zhicwu commented
> @zhicwu do you know why SonarCloud Quality Gate failed? (nothing was changed just removed deprecated api)

The coverage of changed lines is less than 80%. It's the default rule but not mandatory.