Adding performance tests between V1 and V2
ClickHouse/clickhouse-java pull request #1769
Opened 2024-08-12 06:43 UTC by Paultagoras

## Summary

## Checklist
Delete items not relevant to your PR:
- [ ] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

2024-08-12 10:44 UTC, mzitnik reviewed
Can you provide an explanation how to run it

2024-08-12 10:49 UTC, mzitnik commented
Can we also provide some early results just to understand how the output looks like

2024-08-12 16:22 UTC, chernser commented
The medium size query looks suspiciously too good 

```
V1 
ClientBenchmark.queryBenchmarkMedium:p0.00 sample 1602.224 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.50 sample 1701.839 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.90 sample 1816.763 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.95 sample 1863.215 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.99 sample 1864.368 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.999 sample 1864.368 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.9999 sample 1864.368 ms/op

V2
ClientBenchmark.queryBenchmarkMedium:p0.00 sample 118.882 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.50 sample 146.538 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.90 sample 154.927 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.95 sample 156.500 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.99 sample 159.908 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.999 sample 160.694 ms/op
ClientBenchmark.queryBenchmarkMedium:p0.9999 sample 160.694 ms/op
```

2024-08-12 16:25 UTC, chernser commented
The insert too 

```
Insert 

v1
ClientBenchmark.insertRawDataBenchmark:p0.00 sample 28.934 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.50 sample 34.013 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.90 sample 39.059 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.95 sample 42.880 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.99 sample 59.932 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.999 sample 88.595 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.9999 sample 101.057 ms/op
ClientBenchmark.insertRawDataBenchmark:p1.00 sample 101.057 ms/op

v2
ClientBenchmark.insertRawDataBenchmark:p0.00 sample 5.915 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.50 sample 7.700 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.90 sample 9.224 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.95 sample 10.076 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.99 sample 31.977 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.999 sample 53.668 ms/op
ClientBenchmark.insertRawDataBenchmark:p0.9999 sample 177.734 ms/op
```

2024-08-15 05:46 UTC, mzitnik requested changes
Why we do not have parallel insert test

2024-08-15 05:46 UTC, mzitnik commented on client-v2/src/test/perf/com/clickhouse/client/ClientBenchmark.java
> +                .setPassword("")
Does our default is empty ("") seems redundant

2024-08-15 05:46 UTC, mzitnik commented on client-v2/src/test/perf/com/clickhouse/client/ClientBenchmark.java
> +                .setUsername("default")
it should be our default username also looks redundant

2024-08-19 17:00 UTC, mzitnik approved these changes

2024-08-22 15:07 UTC, merged