[client-v2] Initial attempt at adding some server context to the client
ClickHouse/clickhouse-java pull request #2029
Opened 2024-12-17 16:16 UTC by Paultagoras

## Summary
Closes #2027 
Adds a call to gather currentUser(), timezone(), and version() for the client

## Checklist
Delete items not relevant to your PR:
- [x] Closes issue 
- [x] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

2024-12-17 17:09 UTC, chernser commented on client-v2/src/main/java/com/clickhouse/client/api/Client.java
> +    private String serverVersion;
please add `getServerVersion()`

2024-12-17 17:10 UTC, chernser commented on client-v2/src/main/java/com/clickhouse/client/api/Client.java
> +    private String serverVersion;
for the use we need to update `com.clickhouse.client.api.Client#getUser`

2024-12-17 17:11 UTC, chernser requested changes
please correct getters

2024-12-18 07:09 UTC, chernser approved these changes

2024-12-18 07:10 UTC, mzitnik reviewed
General comment i think we should a way to disable if the user wants

2024-12-18 14:15 UTC, merged